merge master with ts_transfer branch
Kucher-mx/mem-crab pull request #1
Opened 2021-07-20 11:57 UTC by Kucher-mx

2021-07-20 13:27 UTC, max-mykhailenko requested changes

2021-07-20 13:27 UTC, max-mykhailenko commented on eslintCfg.js
> +module.exports = {
Странное название конфигурационного файла + не вижу чтобы появился memcrab-eslint-config

2021-07-20 13:27 UTC, max-mykhailenko commented on src/actions/action.tsx
> +const HIGHLITE_SUM = (id: string) => ({type: "HIGHlITE_SUM", id});
Чем тип String отличается от типа string?

2021-07-20 13:27 UTC, max-mykhailenko commented on src/actions/action.tsx
> +const HIGHLITE_SUM = (id: string) => ({type: "HIGHlITE_SUM", id});
Какой из них правильный?

2021-07-20 13:27 UTC, max-mykhailenko commented on src/actions/actionTypes.ts
> +}
Считается ли этот объект константным, используй as const

2021-07-20 13:27 UTC, max-mykhailenko commented on src/components/bottomSidebar/BottomSidebar.component.tsx
> +    const colInfo: number[] = calcColValue(items, table);
: number[] нужно чтобы этот тип был определен как результат работы функции, здесь его прописывать не нужно

2021-07-20 13:27 UTC, max-mykhailenko commented on src/components/bottomSidebar/BottomSidebar.component.tsx
> +export default connect(stateToProps)(BottomSidebar);
connect на сколько помню должен быть описан как generic

2021-07-20 13:27 UTC, max-mykhailenko commented on src/components/buttons/Buttons.component.tsx
> +function mapDispatchToProps(dispatch: (arg0: {type: string}) => {}) {
: (arg0: {type: string} — тип для этой функции необходимо вытянуть с типов react-redux

2021-07-20 13:27 UTC, max-mykhailenko commented on src/index.tsx
> +        (window as any).__REDUX_DEVTOOLS_EXTENSION__ &&
as any необходимо определить тип переменной window в глобальной области видимости, как модуля

2021-07-20 13:27 UTC, max-mykhailenko commented on src/reducer/reducer.ts
> +    actions: {type: string; value?: actionTypes; id?: string | string[]}
Необходимо четко определить возможные варианты екшинов с возможными параметрами, фактически будет что то вида 

actions: {type: some_type, value: string}  | {type: some_another_type, value: number} и тд

2021-07-20 14:41 UTC, Kucher-mx commented on src/actions/action.tsx
> +const HIGHLITE_SUM = (id: string) => ({type: "HIGHlITE_SUM", id});
String это обертка над string - клас с js, а string это тип с typeScript, поэтому лучше использовать string.

2021-07-21 09:55 UTC, closed without merging

2021-07-21 09:58 UTC, Kucher-mx reviewed
ok