Ts transfer (with ssr set up ready)
Kucher-mx/mem-crab pull request #3
Opened 2021-07-29 14:05 UTC by Kucher-mx

2021-08-01 20:43 UTC, max-mykhailenko requested changes
Дал комментарии немного по типам, но больше по реакту

2021-08-01 20:43 UTC, max-mykhailenko commented on src/App.tsx
> +// @ts-ignore
Почему решил использовать здесь игнор?

2021-08-01 20:43 UTC, max-mykhailenko commented on src/App.tsx
> +                    // @ts-ignore
О, еще один игнор

2021-08-01 20:43 UTC, max-mykhailenko commented on src/actions/action.tsx
> +const UNHIGHLITE = (id: string[]) => ({type: ActionTypes.UNHIGHLITE, value: id});
Необходимо проверить грамматику

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/bottomSidebar/BottomSidebar.component.tsx
> +                genSum: 0,
Если внутри используется только один ключ, то почему бы сразу не передать числовое начальное значение?

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/bottomSidebar/BottomSidebar.component.tsx
> +            .reduce((a, b) => ({genSum: a.genSum + b.rowSum}), {
Параметры функции лучше называть более полно и значимо. Принятыми для редюсера считается acc для аккумулятора и любое другое подходящее имя для второго параметра

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/bottomSidebar/BottomSidebar.component.tsx
> +    if (elements.length !== 0) {
Лучше записать это условие в виде тернарного, тогда не придется задавать значение по умолчанию выше и можно будет использовать константу

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/bottomSidebar/BottomSidebar.component.tsx
> +            .reduce((a, b) => ({genSum: a.genSum + b.rowSum}), {
При каждой итерации будет создаваться новый объект, это дорого по производительности

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/bottomSidebar/bottomSidebar.styles.css
> +    /* flex-direction: row;
Комментарии в коде лучше не оставлять, а если все же приходится, то необходимо подписать зачем это сделано и в каких случаях будет использоваться

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/buttons/Buttons.component.tsx
> +function Buttons({add, remove}: IButtons) {
Так как подход у реакта компонентный, то лучше тип называть не от названия компонента, а просто Props

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/buttons/Buttons.component.tsx
> +function Buttons({add, remove}: IButtons) {
Если же делать через интерфейс, то он должен содержать не только аргументы, но и то, что функция возвращает, тогда это будет правильный интерфейс

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/cell/Cell.component.tsx
> +    shouldComponentUpdate(nextProps: ICell) {
Можно написать этот же функционал используя чистую функцию и React.memo с кастомной функцией сравнения

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/cell/Cell.component.tsx
> +export default React.memo(Cell);
Часто указать мемо недостаточно, необходимо еще передать функцию, которая будет сравнивать предыдущие и текущие пропсы

2021-08-01 20:43 UTC, max-mykhailenko commented on src/components/leftSidebar/LeftSidebar.component.tsx
> +                        onMouseLeave={e => {
Создается избыточная анонимная функция, так как внутри кроме вызова основной ничего не происходит

2021-08-01 20:43 UTC, max-mykhailenko commented on src/pages/main/Main.component.tsx
> +        while (cellsToHighlite.length <= items.X) {
Это мы перепишем в другой итерации )

2021-08-01 20:43 UTC, max-mykhailenko commented on src/pages/main/Main.component.tsx
> +        const cellToUnhighlite = [...tempArr.filter(el => el.isHighlited).map(el => el.id)];
И фильтры и мэп создают новые массивы, зачем деструктуризация?

2021-08-01 20:43 UTC, max-mykhailenko commented on src/pages/main/Main.component.tsx
> +                <Table table={table} hoverEnter={inHoverCellHandle} hoverOut={outHoverCellHandle} click={increase} />
Передавать функции обработчики в глубь компонентов без обертки useCallback не стоит, так как это будет провоцировать очень большое количество повторных рендеров всего дерева

2021-08-01 20:43 UTC, max-mykhailenko commented on src/pages/start/Start.component.tsx
> +        e.persist();
Что делает этот персист и почему он нужен?

2021-08-01 20:43 UTC, max-mykhailenko commented on src/reducer/reducer.ts
> +            };
Возможно стоит рассмотреть хранение данных в немного другом виде? Очень уж глубоко приходится лезть чтобы сделать такие частые изменения как наведение или клик по ячейке

2021-08-02 06:11 UTC, Kucher-mx commented on src/App.tsx
> +                    // @ts-ignore
ts-ignore использовал потому что ts ругается на такой вызов компонента, без параметров: 
![photo_2021-08-02 09 11 23](https://user-images.githubusercontent.com/51436439/127812346-9ca9a89b-7206-402f-a4b6-62ee6bf5b509.jpeg)

2021-08-02 06:39 UTC, Kucher-mx commented on src/pages/start/Start.component.tsx
> +        e.persist();
По факту он не нужен, я просто забыл его убрать, ставил, потому что были проблемы что е.target === null, а так то он используется, когда мы хотим использовать ивент в асинхронном коде

2021-08-06 12:20 UTC, Kucher-mx commented
reopened

2021-08-06 15:47 UTC, max-mykhailenko requested changes

2021-08-06 15:47 UTC, max-mykhailenko commented on src/pages/main/Main.component.tsx
> +    );
HOVER

const table = [[{}, {}, {highlight: true, id: 8}] x100 ]; x 100 => 10000

const highlight = {10: {8: true, 9: true}, 11: {12: true}}

unhighlight = () =>  highlight = {};

Rows highlight={highlight}
<Cell highlight={highlight[id] } />

CLICKS

TODO лекция дена абрамова по редаксу egghead

2021-08-09 08:07 UTC, max-mykhailenko approved these changes

2021-08-09 08:07 UTC, max-mykhailenko commented on src/pages/main/Main.component.tsx
> +            const hoveredStart = hoverElementIdx - items.X < 0 ? 0 : hoverElementIdx - items.X;
math.max() нормас работает

2021-08-09 08:07 UTC, max-mykhailenko commented on src/pages/main/Main.component.tsx
> +            const hoveredEnd =
math.min(arr.length, I + X) нормас работает

2021-08-09 08:07 UTC, max-mykhailenko commented on src/pages/main/Main.component.tsx
> +                .filter((_, idx) => idx >= hoveredStart && idx <= hoveredEnd)
фильтр намного медленнее будет чем слайс

2021-08-09 08:07 UTC, max-mykhailenko commented on src/pages/main/Main.component.tsx
> +                        acc[rowId] = {...acc[rowId], [cellId]: true};
деструктуризация это клево, но здесь у тебя одно из критических мест по производительности + ты создаешь объект с нуля, предлагаю мутировать аккумулятор в целях производительности

2021-08-09 08:53 UTC, merged